### ISSUE TITLE
"HERE COMES A NEW CHALLENGER!" Not Playing

### ISSUE THREAD

**Issue by Hansukie** [Infinest/Super-Street-Fighter-2-MD-Plus#1]
When playing on real hardware on a Mega Everdrive Pro, for some reason, the "Here comes a new challenger!" track doesn't play when it should. It's just silent. Tried the 3DO and X68k versions and they both have the bug. 

Tried them using Genesis GX Plus on Retroarch, same result.

**Comment by Infinest** [comment]
I've just tried triggering the track via the debug menu and it seems to be playing properly there.
Can you specify when exactly during normal gameplay the track should play?

**Comment by Hansukie** [comment]
> I've just tried triggering the track via the debug menu and it seems to be playing properly there. Can you specify when exactly during normal gameplay the track should play?

It does play when selecting the track in the debug menu sound test.

However, the track does not play when Player 2 joins during gameplay. 

When it says "Press Start" on the player 2 side when player 1 is playing through the game. Pressing Start on player 2's controller, the currently playing music stops, the text "HERE COMES A NEW CHALLENGER!" pops up, and that's when the track should play. It does not.

**Comment by Infinest** [comment]
I think i found the problem. For some odd reason the game does trigger the new challenger track but immediately fires a stop command right after. Can you give this version a try?
[patch.zip](https://github.com/user-attachments/files/16119834/patch.zip) (Had to put the IPS file into a ZIP because Github wouldn't let me upload it otherwise)

**Comment by Hansukie** [comment]
Tested the new patch and the track plays when it's supposed to now. Great! 

Thanks a lot for fixing this!

**Comment by Infinest** [comment]
You're welcome! Good to hear it's fixed.
I'll close this issue then. I'll publish the new version later today or tomorrow.
